# Generated by Django 5.0.2 on 2024-03-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_to_answer',
            field=models.IntegerField(default=60),
        ),
    ]
