# Generated by Django 5.0.2 on 2024-03-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0003_uniquecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='unique_code',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
