# Generated by Django 5.0.2 on 2024-03-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
