# Generated by Django 5.0.2 on 2024-04-29 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='time_to_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='unique_code',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam1.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_answer', models.IntegerField()),
                ('unique_code', models.CharField(max_length=50)),
                ('correct_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam1.option')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam1.question')),
            ],
        ),
    ]
