# Generated by Django 5.0.2 on 2024-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam1', '0008_remove_question_correct_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondetail',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='questiondetail',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default=6, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='time_to_answer',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='question',
            name='unique_code',
            field=models.CharField(default=7, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='QuestionDetail',
        ),
    ]
